services:
  kurrentdb.db:
    image: docker.kurrent.io/kurrent-latest/kurrentdb:latest
    environment:
      - KURRENTDB_CLUSTER_SIZE=1
      - KURRENTDB_RUN_PROJECTIONS=All
      - KURRENTDB_START_STANDARD_PROJECTIONS=true
      - KURRENTDB_NODE_PORT=2113
      - KURRENTDB_INSECURE=true
      - KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '2113:2113'
    volumes:
      - type: volume
        source: kurrentdb-volume-data
        target: /var/lib/kurrentdb
      - type: volume
        source: kurrentdb-volume-logs
        target: /var/log/kurrentdb

  mongodb.db:
    image: mongo:7
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: mongodb-volume-data
        target: /data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "rs.status().ok"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  mongodb.init:
    image: mongo:7
    depends_on:
      mongodb.db:
        condition: service_started
    command: >
      sh -c "
      sleep 5 &&
      mongosh --host mongodb.db:27017 --eval
      \"rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb.db:27017'}]})\"
      "
    restart: on-failure

volumes:
  kurrentdb-volume-data:
  kurrentdb-volume-logs:
  mongodb-volume-data:
